Attempt to fix 'Premature end of file' #6
 - Upgrade to new carml version 0.4.8
 - Setup and run carml only if the source attachment is not blank
 - Blank mapping attachments yield HTTP 400 instead of HTTP 500 (catch
RmlMapperException: No actionable triples maps provided)